version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - my_postgres_data:/var/lib/postgresql/data # Persist data even when container shuts down
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  my_postgres_data:
